module.exports= {
    products:[{
        _id:'1',
        name:'Slim Shirt',
        category:'Shirts',
        image:'/images/d1.jpg',
        price:60,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        countInStock:10,
    },
    {
        _id:'2',
        name:'Fit Shirt',
        category:'Shirts',
        image:'/images/d1.jpg',
        price:50,
        brand:'Nike',
        rating:4.0,
        numReviews:10,
        countInStock:10,
    },
    {
        _id:'3',
        name:'Best Pants',
        category:'Pants',
        image:'/images/d1.jpg',
        price:70,
        brand:'Nike',
        rating:4.3,
        numReviews:10,
        countInStock:5,
    },
    {
        _id:'4',
        name:'Best Pants',
        category:'Pants',
        image:'https://www.lafuma.com/media/catalog/product/cache/18/image/9df78eab33525d08d6e5fb8d27136e95/l/f/lfv11318-2768-pantalon-homme-access-cargo-pants-m-beige_1.jpg',
        price:70,
        brand:'Nike',
        rating:4.3,
        numReviews:10,
        countInStock:9,
    },
]
}
